module.exports = {
  env: {
      "BASE_URL": "https://www.projetovidamendes.com",
      "MYSQL_URL": "http://localhost:3005",
      "LOCAL_URL": "http://localhost:3000",
      "MONGODB_URL": "mongodb+srv://projetovidamendes:pvmendes1705@cluster0.m0mxv.mongodb.net/pvmendes?retryWrites=true&w=majority",
      "ACCESS_TOKEN_SECRET": "YOUR_ACCESS_TOKEN_SECRET",
      "REFRESH_TOKEN_SECRET": "YOUR_REFRESH_TOKEN_SECRET",
      "PAYPAL_CLIENT_ID": "YOUR_PAYPAL_CLIENT_ID",
      "CLOUD_UPDATE_PRESET": "YOUR_CLOUD_UPDATE_PRESET",
      "CLOUD_NAME": "YOUR_CLOUD_NAME",
      "CLOUD_API": "YOUR_CLOUD_API",
      "EMAILJS_SERVICE": "service_ikge4sk",
      "EMAILJS_KEY": "8Hh2hSzRwdOGAe58h",
      "YOUTUBE_API_URL": "https://www.googleapis.com/youtube/v3",
      "YOUTUBE_API_KEY": "AIzaSyAw23FsktydNkybVzv4YSHsBkO95RUEPkQ",
      "CHANNEL_ID": "UCFAGz-_BGnaRnQ-Rh0RJ2Hw",
      "ABOUT_ID": "627a6ff3d0c165fbf72e0e3f",
      "TOKEN" : "K1a6l0l3a",
      "MYSQL_HOST"    : "127.0.0.1",
      "MYSQL_PORT"    : "3306",
      "MYSQL_DATABASE": "projetovidamendes_production",
      "MYSQL_USER"    : "root",
      "MYSQL_PASSWORD": "16031973",
  }
}